sudo: required

language:
  - cpp

compiler:
  - gcc

install:
    - sudo add-apt-repository ppa:lkoppel/opencv -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt update
    - sudo apt install libopencv-dev
    - sudo apt install cmake
    - sudo apt install gcc-7

script:
  - mkdir build && cd build
  - cmake ..
  - make checkstyle
  - make -j
  - ctest -j
